# Generated by Django 4.2.7 on 2023-11-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('rooms', models.IntegerField(verbose_name='No. of rooms')),
            ],
        ),
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('fee', models.CharField(help_text='Input fee if there is any', max_length=4, verbose_name='Entrance Fee')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='carHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25, verbose_name='Car Make')),
                ('model', models.CharField(max_length=25, verbose_name='Car Model')),
                ('seater', models.IntegerField(verbose_name='Seater')),
                ('price', models.IntegerField(verbose_name='Hiring Price')),
            ],
        ),
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Location')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
    ]
