# Generated by Django 4.2.7 on 2023-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhire',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Car Image'),
        ),
        migrations.AddField(
            model_name='carhire',
            name='plate',
            field=models.CharField(default=1, max_length=8, verbose_name='Number Plate'),
            preserve_default=False,
        ),
    ]
