# Generated by Django 4.2.7 on 2023-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0004_carhire_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Location')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='destinations',
        ),
        migrations.AlterField(
            model_name='carhire',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Car Description'),
        ),
    ]
