# Generated by Django 4.2.7 on 2023-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0005_destination_delete_destinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('fee', models.CharField(help_text='Input fee if there is any', max_length=4, verbose_name='Entrance Fee')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='attractions',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
