# Generated by Django 4.2.7 on 2023-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0006_attraction_delete_attractions_accommodation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=15, verbose_name='Surname')),
                ('image', models.CharField(max_length=15, verbose_name='Middle Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
            ],
        ),
    ]
