# Generated by Django 4.2.7 on 2023-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0008_destination_link_alter_guide_age_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='link',
            field=models.URLField(verbose_name='Google Maps Link'),
        ),
    ]
