# Generated by Django 4.2.7 on 2023-11-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0009_alter_destination_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Describe yourself'),
        ),
    ]
