# Generated by Django 4.2.7 on 2023-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0012_travelpackages_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackages',
            name='was',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Former Price'),
        ),
    ]
