# Generated by Django 4.2.7 on 2023-11-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karibu_Kilifi', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
